CLASS ZCL_FI_SOCTCN DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES IF_RAP_QUERY_PROVIDER.

    "data type range of
    DATA:
      GR_COMPANYCODE  TYPE RANGE OF BUKRS,
      GR_FISCALYEAR   TYPE RANGE OF FIS_GJAHR_NO_CONV,
      GR_GLACCOUNT    TYPE RANGE OF SAKNR,
      GR_CUS_SUP      TYPE RANGE OF KUNNR,
      GR_WAERS        TYPE RANGE OF WAERS,
      GR_ACCOUNTGROUP TYPE RANGE OF KTOKD
      .

    "data parameter
    DATA:
      LV_KOART    TYPE KOART,
      GR_KOART    TYPE RANGE OF KOART,
      LV_INREV    TYPE ZDE_YESNO,
      LV_DOCTYPE  TYPE ZDE_YESNO,
      LV_SUMTK    TYPE ZDE_YESNO,
      LV_FROMDATE TYPE DATS,
      LV_TODATE   TYPE DATS,
      LV_OPT      TYPE ZDE_OPT_IN_SOCTCN.


    "table type
    DATA: GT_DATA TYPE TABLE OF ZFI_I_SOCHITIETCONGNO_CUS,
          GS_DATA LIKE LINE OF  GT_DATA.

